name = "test"
main = "index.js"
compatibility_date = "2025-03-10"

[[d1_databases]]
binding = "DB"
database_name = "test"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id = "1abd9653-6b2e-48a8-8c08-aa78473046a6"

[triggers]
crons = ["0 2 */1 * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "test"
database_id = "1abd9653-6b2e-48a8-8c08-aa78473046a6"

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"
